#!/usr/bin/env zsh

# Change theming from dark to light or vice versa

if [[ $(gsettings get org.gnome.desktop.interface color-scheme) =~ .*dark.* ]]; then
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
    gsettings set org.gnome.desktop.interface color-scheme default
else
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
fi
